/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserApplicationData } from './user-application-data';
import { UserCalendar } from './user-calendar';
import { UserCulture } from './user-culture';
import { UserDepartment } from './user-department';
import { UserHabilitedRolesInner } from './user-habilited-roles-inner';
import { UserLegalEntity } from './user-legal-entity';
import { UserManager } from './user-manager';
import { UserPicture } from './user-picture';
import { UserRolePrincipal } from './user-role-principal';
import { UserUserWorkCyclesInner } from './user-user-work-cycles-inner';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'displayName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'modifiedOn': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'login': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'mail': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'dtContractStart': string;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'dtContractEnd'?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'birthDate': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'employeeNumber': string;
    /**
     * 
     * @type {UserCalendar}
     * @memberof User
     */
    'calendar': UserCalendar;
    /**
     * 
     * @type {UserCulture}
     * @memberof User
     */
    'culture': UserCulture;
    /**
     * 
     * @type {UserPicture}
     * @memberof User
     */
    'picture': UserPicture;
    /**
     * 
     * @type {UserApplicationData}
     * @memberof User
     */
    'applicationData': UserApplicationData;
    /**
     * 
     * @type {UserLegalEntity}
     * @memberof User
     */
    'legalEntity': UserLegalEntity;
    /**
     * 
     * @type {UserDepartment}
     * @memberof User
     */
    'department': UserDepartment;
    /**
     * 
     * @type {UserManager}
     * @memberof User
     */
    'manager': UserManager;
    /**
     * 
     * @type {UserRolePrincipal}
     * @memberof User
     */
    'rolePrincipal': UserRolePrincipal;
    /**
     * 
     * @type {Set<UserHabilitedRolesInner>}
     * @memberof User
     */
    'habilitedRoles': Set<UserHabilitedRolesInner>;
    /**
     * 
     * @type {Set<UserUserWorkCyclesInner>}
     * @memberof User
     */
    'userWorkCycles': Set<UserUserWorkCyclesInner>;
}

