/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserUserWorkCyclesInner
 */
export interface UserUserWorkCyclesInner {
    /**
     * 
     * @type {number}
     * @memberof UserUserWorkCyclesInner
     */
    'Id': number;
    /**
     * 
     * @type {number}
     * @memberof UserUserWorkCyclesInner
     */
    'OwnerID': number;
    /**
     * 
     * @type {number}
     * @memberof UserUserWorkCyclesInner
     */
    'WorkCycleID': number;
    /**
     * 
     * @type {string}
     * @memberof UserUserWorkCyclesInner
     */
    'StartsOn': string;
    /**
     * 
     * @type {string}
     * @memberof UserUserWorkCyclesInner
     */
    'EndsOn': string;
}

