/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Null } from './null';
import { UsersListExcludedFormerResponseItemsInnerCalendar } from './users-list-excluded-former-response-items-inner-calendar';
import { UsersListExcludedFormerResponseItemsInnerCulture } from './users-list-excluded-former-response-items-inner-culture';
import { UsersListExcludedFormerResponseItemsInnerPicture } from './users-list-excluded-former-response-items-inner-picture';
import { UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner } from './users-list-excluded-former-response-items-inner-user-work-cycles-inner';

/**
 * 
 * @export
 * @interface UsersListExcludedFormerResponseItemsInner
 */
export interface UsersListExcludedFormerResponseItemsInner {
    /**
     * 
     * @type {number}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'modifiedOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'login'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'mail'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'dtContractStart'?: string;
    /**
     * 
     * @type {Null}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'dtContractEnd'?: Null;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'birthDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'employeeNumber'?: string;
    /**
     * 
     * @type {UsersListExcludedFormerResponseItemsInnerCalendar}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'calendar'?: UsersListExcludedFormerResponseItemsInnerCalendar;
    /**
     * 
     * @type {UsersListExcludedFormerResponseItemsInnerCulture}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'culture'?: UsersListExcludedFormerResponseItemsInnerCulture;
    /**
     * 
     * @type {UsersListExcludedFormerResponseItemsInnerPicture}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'picture'?: UsersListExcludedFormerResponseItemsInnerPicture;
    /**
     * 
     * @type {object}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'applicationData'?: object;
    /**
     * 
     * @type {UsersListExcludedFormerResponseItemsInnerCulture}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'legalEntity'?: UsersListExcludedFormerResponseItemsInnerCulture;
    /**
     * 
     * @type {UsersListExcludedFormerResponseItemsInnerCulture}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'department'?: UsersListExcludedFormerResponseItemsInnerCulture;
    /**
     * 
     * @type {UsersListExcludedFormerResponseItemsInnerCulture}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'manager'?: UsersListExcludedFormerResponseItemsInnerCulture;
    /**
     * 
     * @type {UsersListExcludedFormerResponseItemsInnerCulture}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'rolePrincipal'?: UsersListExcludedFormerResponseItemsInnerCulture;
    /**
     * 
     * @type {Array<UsersListExcludedFormerResponseItemsInnerCulture>}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'habilitedRoles'?: Array<UsersListExcludedFormerResponseItemsInnerCulture>;
    /**
     * 
     * @type {Array<UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner>}
     * @memberof UsersListExcludedFormerResponseItemsInner
     */
    'userWorkCycles'?: Array<UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner>;
}

