/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersUpdateByIdRequestUserWorkCyclesInner
 */
export interface UsersUpdateByIdRequestUserWorkCyclesInner {
    /**
     * 
     * @type {number}
     * @memberof UsersUpdateByIdRequestUserWorkCyclesInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersUpdateByIdRequestUserWorkCyclesInner
     */
    'startsOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUpdateByIdRequestUserWorkCyclesInner
     */
    'endsOn'?: string;
    /**
     * 
     * @type {number}
     * @memberof UsersUpdateByIdRequestUserWorkCyclesInner
     */
    'workCycleId'?: number;
}

