/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner
 */
export interface UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner {
    /**
     * 
     * @type {number}
     * @memberof UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner
     */
    'Id'?: number;
    /**
     * 
     * @type {number}
     * @memberof UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner
     */
    'OwnerID'?: number;
    /**
     * 
     * @type {number}
     * @memberof UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner
     */
    'WorkCycleID'?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner
     */
    'StartsOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner
     */
    'EndsOn'?: string;
}

