/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Null } from './null';
import { UsersGetByIdResponseCalendar } from './users-get-by-id-response-calendar';
import { UsersGetByIdResponseCulture } from './users-get-by-id-response-culture';
import { UsersGetByIdResponseDepartment } from './users-get-by-id-response-department';
import { UsersGetByIdResponseLegalEntity } from './users-get-by-id-response-legal-entity';
import { UsersGetByIdResponseManager } from './users-get-by-id-response-manager';
import { UsersGetByIdResponsePicture } from './users-get-by-id-response-picture';
import { UsersGetByIdResponseRolePrincipal } from './users-get-by-id-response-role-principal';
import { UsersListExcludedFormerResponseItemsInnerCulture } from './users-list-excluded-former-response-items-inner-culture';
import { UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner } from './users-list-excluded-former-response-items-inner-user-work-cycles-inner';

/**
 * 
 * @export
 * @interface UsersGetByIdResponse
 */
export interface UsersGetByIdResponse {
    /**
     * 
     * @type {number}
     * @memberof UsersGetByIdResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'modifiedOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'login'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'mail'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'dtContractStart'?: string;
    /**
     * 
     * @type {Null}
     * @memberof UsersGetByIdResponse
     */
    'dtContractEnd'?: Null;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'birthDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponse
     */
    'employeeNumber'?: string;
    /**
     * 
     * @type {UsersGetByIdResponseCalendar}
     * @memberof UsersGetByIdResponse
     */
    'calendar'?: UsersGetByIdResponseCalendar;
    /**
     * 
     * @type {UsersGetByIdResponseCulture}
     * @memberof UsersGetByIdResponse
     */
    'culture'?: UsersGetByIdResponseCulture;
    /**
     * 
     * @type {UsersGetByIdResponsePicture}
     * @memberof UsersGetByIdResponse
     */
    'picture'?: UsersGetByIdResponsePicture;
    /**
     * 
     * @type {object}
     * @memberof UsersGetByIdResponse
     */
    'applicationData'?: object;
    /**
     * 
     * @type {UsersGetByIdResponseLegalEntity}
     * @memberof UsersGetByIdResponse
     */
    'legalEntity'?: UsersGetByIdResponseLegalEntity;
    /**
     * 
     * @type {UsersGetByIdResponseDepartment}
     * @memberof UsersGetByIdResponse
     */
    'department'?: UsersGetByIdResponseDepartment;
    /**
     * 
     * @type {UsersGetByIdResponseManager}
     * @memberof UsersGetByIdResponse
     */
    'manager'?: UsersGetByIdResponseManager;
    /**
     * 
     * @type {UsersGetByIdResponseRolePrincipal}
     * @memberof UsersGetByIdResponse
     */
    'rolePrincipal'?: UsersGetByIdResponseRolePrincipal;
    /**
     * 
     * @type {Array<UsersListExcludedFormerResponseItemsInnerCulture>}
     * @memberof UsersGetByIdResponse
     */
    'habilitedRoles'?: Array<UsersListExcludedFormerResponseItemsInnerCulture>;
    /**
     * 
     * @type {Array<UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner>}
     * @memberof UsersGetByIdResponse
     */
    'userWorkCycles'?: Array<UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner>;
}

