/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserApplicationDataProfileFiggo } from './user-application-data-profile-figgo';
import { UserApplicationDataProfileUtime } from './user-application-data-profile-utime';

/**
 * 
 * @export
 * @interface UserApplicationData
 */
export interface UserApplicationData {
    /**
     * 
     * @type {UserApplicationDataProfileFiggo}
     * @memberof UserApplicationData
     */
    'profile_figgo': UserApplicationDataProfileFiggo;
    /**
     * 
     * @type {UserApplicationDataProfileUtime}
     * @memberof UserApplicationData
     */
    'profile_utime': UserApplicationDataProfileUtime;
}

