/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersGetByIdResponseCulture
 */
export interface UsersGetByIdResponseCulture {
    /**
     * 
     * @type {number}
     * @memberof UsersGetByIdResponseCulture
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponseCulture
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGetByIdResponseCulture
     */
    'url'?: string;
}

