/*
Directory-v3

Welcome on the documentation for the Directory v3 API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserDepartment
 */
export interface UserDepartment {
    /**
     * 
     * @type {number}
     * @memberof UserDepartment
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserDepartment
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserDepartment
     */
    'url': string;
}

